theme: jekyll-theme-minimal
title: "nauleyco"
description: "@nauleyco<br>
I am a PHP developer. <br>
i ℒℴѵℯ php ♡ i ℒℴѵℯ boeing ♡. <br>
I am a member of JAPAN PHP User Group. <br>
Please join us!"
logo: "/assets/images/icon.jpg"
