theme: jekyll-theme-minimal
title: "nauleyco"
description: "@nauleyco
I am a PHP developer. 
i ℒℴѵℯ php ♡ i ℒℴѵℯ boeing ♡. 
I am a member of JAPAN PHP User Group. 
Please join us!"
logo: "/assets/images/icon.jpg"
show_downloads: "false"
